### ISSUE TITLE
new dat-ecosystem website project plan

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#12]
## `@todo`
- [x] Study Road map guide
  - Explanation of this roadmap
    - `@output` :package: [Screencast -explanation:](https://www.loom.com/share/cac30f7fca954d858684e1aa625e8df0)
- [x]  Road map 
 #13 

---

## Summary
This directory contains a roadmap to building the the new dat-ecosystem website
### Mission:
Our mission is to foster the decentralized [garden](https://hackmd.io/6T6MwxU8SSefMiQsusFVvg#glossary) by empowering initiatives and projects that have a clear positive social impact, such as [civic tech, marginalized communities and science](https://hackmd.io/6T6MwxU8SSefMiQsusFVvg#civic-tech-marginalized-communities-and-science) with p2p technologies which are secure, local-first, interoperable, easy-to-use, and fast.

**Comment by Hornet004** [comment]
- [ ] `@output` :question: from `new dat-ecosystem website project plan issue`

**Comment by serapath** [comment]
**feedback `2022.04.26`**

Heya :-)
It looks interesting, but also quite abstract.

1. the `new dat-ecosystem website project plan` is what should be the outcome of this trial phase, which should then have maybe a figma wireframe as an output

2. UX research sounds good, but `problem definition` sounds also quite abstact. I was kinda hoping a problem refinement could of course happen later, but the trial phase might already be there to figure this out ...and is there even a problem? 

3. what exactly is a `solution` ? ...is that the website? ...and where was the `concept` that gets `validated`? ...and what are the validation criteria? where they worked on?
...i mean, it is dat-ecosystem and it needs a website and i feel thats quite specific and tangible already, while "solution", "validation", etc... is way to abstract for my taste

4. the product design sounds good, but that will give me wireframes again? ...i thought we have that earlier already. Is that again figma?

5. this step makes sense to me, but it turns in a single todo step the "wireframe" into the "final page" :-) ...i guess it makes sense as a first iteration of the project plan that i can give feedback on, but because not a single of the listed "resource link" or "group of resource links" has been added as an `input` for some of the todos, it is hard for me to give any more specific feedback

---

What are the parts or aspects or categories or "page" or "components" or whatever you call it that should be in the webapp/website page to solve or display or show which of the resources? ...of course getting more specific can "go wrong", but it would be a first iteration and "best guess" of what would maybe be relevant to include in the website/webapp ...and then i could give feedback and we do another iteration.

This project plan is "fail safe" or "bullet proof" in that it is definitely correct, because everyone wants their problem to be defined and wants the solution and wants it validated - it is so general, that it is always correct, but it doesn't say anything about what that means for the specific project at hand, so i would rather see a more specific and adapted version to the project at hand that might have lots of mistakes or prioritises things in the wrong way or whatever, but exactly because of that i can share some thoughts and give some feedback of how to iterate to make it better.

This **process* of having something more opinionated and specific and me being able to give feeedback of how to iterate on it to improve it is what I think is the best way to over time get onto the same page - basically to slowly get a shared understanding of what the website should be, based on the professional input and work and me as a "customer" or "client" to steer that to match my or rather the "end user" needs that i can represent.

But :+1: for the format - it looks good

**Comment by Hornet004** [comment]
Oh no worries, I'll make the necessary changes and edit the Info section to include additional context.

**Comment by serapath** [comment]
> Oh no worries, I'll make the necessary changes and edit the Info section to include additional context.

I think one goal would be to have more than one issue and link those new additional issues as todos in this main one here.
  * https://github.com/wizardamigos/wizardamigos.github.io/issues/38
  * https://github.com/datdotorg/datdot-ui/issues/1

these are two example links to show you how complex an issue structure for a real world plan can get.

**maybe one goal** should be to include every single resource link and make them inputs of one of those todos in this main issue or a linked sub issue, so we are sure to somehow process all of them ...and the corresponding planned outputs somehwat reflect what we try to achieve as an output when we process those resource links in the trial phase description

**Comment by serapath** [comment]
merged into #49
