### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#20]
## `@todo`

- [ ] Make a Style Guide for dat ecosystem website (3 days)
  * `@input`❓`Link to user flow chart` from #19 
  * `@input` 📦 [old styleguide](https://dat-ecosystem-archive.github.io/design/)
  * `@input` 📦 [dat colors](https://github.com/dat-ecosystem/dat-colors)
   * `@output`❓`Colors`
   * `@output`❓`Grids`
   * `@output`❓`Typography`
- [ ] Create UI Components (2 days)
   * `@input` 📦 [old web icon elements](https://github.com/dat-ecosystem-archive/dat-elements)
   * `@input` 📦 [more old icons](https://github.com/dat-ecosystem/dat-icons/tree/master/icons)
   * `@input`❓`Colors`
   * `@input`❓`Grids`
   * `@input`❓`typography`
   * `@output`❓`icons`
   * `@output`❓`buttons`
   * `@output`❓`textholder`
     * Next #21

## `@info`
Here, the design system for dat ecosystem website is being created. These include style guide for the website and the UI components for the website. Inspirations was gotten from:
[101 Design system](https://www.nngroup.com/articles/design-systems-101/) , [The importance of style guide](https://www.grammarly.com/blog/style-guide/) , [Elements](https://www.usability.gov/how-to-and-tools/methods/user-interface-elements.html)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

wonderful.
This sounds good.
**but:**
1. i couldn't see where `colors, typography, grids` (you could make also 3 seperate outputs for them) ....
   * but where are they used as inputs?
2. same for the UI components :-)
3. also do you need any inputs to make or decide how to do that? those are not listed

**Comment by serapath** [comment]
**feedback `2022.04.27`**

This seems perfect.

1. I don't know if you plan to use any additional inputs here from previous todos of other issues, because you mentioned that in #19 so maybe you might wanna add them here?

2. Oh, otherwise, I just wonder where exactly would the outputs here be used?
The only one that you marked is `textholders` as being re-used in #21 but i cant see it as an input there. maybe you can edit and fix that the way you intended it?

**Comment by serapath** [comment]
merged into #49
