### ISSUE TITLE
Web UI Development

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#22]
## `@todo`

- [ ] Implementation of the UI design (10 days)
  * `@input`❓`Link to high fidelity design` from #21 
  * `@output`❓:checkered_flag: `a working high fidelity Design (New dat ecosystem website)`
     * Next #31 
     
## `@info`
At this stage, the high fidelity Design is being developed in order to result to a working New dat ecosystem website.
Getting inspirations from : [Engineers Guide](https://uxdesign.cc/ui-design-implementation-guideline-for-engineers-and-designers-158afbab680a) , [Process of implementing](https://css-tricks.com/the-process-of-implementing-a-ui-design-from-scratch/) , [Steps to successfully implementation](https://360degreecloud.com/steps-to-successful-ui-ux-design-implementation/)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

lovely :-)
...still, formatting needs fixing and otherwise, it kinda makes sense, but i was checking the other issues and could not find anywhere the `@output` :question: `High fidelity Design`, so where is that coming from?
Otherwise, i love it. ...i assume the output is the final output, so thats great.

I didn't say that yet, but final outputs can also include a second icon, which is: :checkered_flag: 
So i added that for you above and in case you plan something else and this is not yet meant to be the final output, then please feel free to undo that change :-)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

yes, lovely :-)
you even marked the final output. that is great.
a tiny detail i mentioned in the previous feedback is the missing

> `@input` :question: `link to high fidelity design` from #21

at the end of the input, just to indicate where that input is coming from.

but otherwise :100: :+1: :star_struck:

**Comment by serapath** [comment]
merged into #49
