### ISSUE TITLE
solution concept files

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#23]
## `@todo`
- [ ] `@input` ❓ `solution concept files` from #3
- [ ] `output` ❓ #26 
    - next #14 

---

### Summary
In this directory, we try to process the information provided from #3  , filter, and put them together for validation.
### `solution concept`
- Utilize the information provided to arrange and produce structured contents/material, as well as to connect the pieces for validation.
- This gives more info on how `wireframes/Iterations` is going to look like and how the contents are going to be structured within it.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

:sweat_smile: i think this one has the same issue as previously other issues.
1. inputs and outputs should never have check boxes, because they are not todos
2. there should be a todo though under which the inputs are listed
3. also the `output` has a missing `@` prefix :-)

good example issues where things are correctly set up are:
* #12
* #13 
* #15 (this one is a very good example)
* #14
* #16

Every issue should have `todo`s, `@input`s, `@output`s and `from` or `next` set up like in those example tasks.

**Comment by serapath** [comment]
merged into #49
