### ISSUE TITLE
concept Validation

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#26]
## `@todo`
  - [ ] `@input` ❓ `concept Validation` from #23
  - [ ] `@output` ❓ #14
    - next #14 

---

### Summary
In this directory, we try to process the information provided from #3  , filter, and put them together for validation.
### `concept Validation`
- the concept is validated and we proceed to create `wireframes/Iterations`

**Comment by serapath** [comment]
**feedback `2022.04.27`**

:sweat_smile: i think this one has the same issue as previously other issues.
1. inputs and outputs should never have check boxes, because they are not todos
2. there should be a todo though under which the inputs are listed

good example issues where things are correctly set up are:
* #12
* #13 
* #15 (this one is a very good example)
* #14
* #16

Every issue should have `todo`s, `@input`s, `@output`s and `from` or `next` set up like in those example tasks.

**Comment by serapath** [comment]
merged into #49
