### ISSUE TITLE
wireframes/Iterations

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#27]
## `@todo`
- [ ] `@input` ❓ `wireframes/Iterations` from #14 
- [ ] `@output` ❓ #28  
  - next # 

---

### Summary
In this directory, we use the information provided from #14   to structure wireframes and create the actual design.
### `wireframes/Iterations`
- Prepare wireframes for validations using Figma.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

:sweat_smile: i think this one has the same issue as previously other issues.
1. inputs and outputs should never have check boxes, because they are not todos
2. there should be a todo though under which the inputs are listed

good example issues where things are correctly set up are:
* #12
* #13 
* #15 (this one is a very good example)
* #14
* #16

Every issue should have `todo`s, `@input`s, `@output`s and `from` or `next` set up like in those example tasks.

**Comment by serapath** [comment]
merged into #49
