### ISSUE TITLE
wireframe validation

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#28]
## `@todo`
- [ ] `@input` ❓ `wireframes validation` from #27  
  - [ ] `@output` ❓ #29 
    - next #16  

---

### Summary
In this directory, we use the information provided from #14   to structure wireframes and create the actual design.
### `wireframes/Iterations`
- Prepare wireframes for validations using Figma.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

:sweat_smile: i think this one has the same issue as previously other issues.
1. inputs and outputs should never have check boxes, because they are not todos
2. there should be a todo though under which the inputs are listed
3. also input and output should have the same indentation level
    * output should not be a sub bullet point of input
    * because output and input bullet points are always both sub bullet points of a todo

good example issues where things are correctly set up are:
* #12
* #13 
* #15 (this one is a very good example)
* #14
* #16

Every issue should have `todo`s, `@input`s, `@output`s and `from` or `next` set up like in those example tasks.

**Comment by serapath** [comment]
merged into #49
